swagger:
  details:
    info:
      title: Product Catalouge service
      version: V 1.0.0
    contact:
      name: Rakesh Jena
      email: iamrkj91@gmail.com
    termsOfService: www.localhost.com
spring:
  datasource:
    url: jdbc:h2:file:~/product-catalouge;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8088
